spring.application.name=S53_2400032619_skill-12




#configure server port with different id
server.port=8080

#configure db properties
spring.datasource.url=jdbc:mysql://localhost:3306/S53_2400032619_skill12
spring.datasource.username=root
spring.datasource.password=root

#configure hibernate and jpa properties
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update